title: Just the Docs Template
# description: A starter template for a Jeykll site using the Just the Docs theme!
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.6.1


url: 

search_enabled: true
verbose: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'

back_to_top: true
back_to_top_text: "Back to top"
footer_content: "As"


callouts:
 highlight:
  color: yellow
 important:
  title: Important
  color: blue

enable_copy_code_button: true

mermaid:
 version: "11.4.1"


# url: https://just-the-docs.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
